language: cpp
sudo: required
os:
- linux
#- osx
addons:
  apt:
    packages:
      - doxygen
branches:
  only:
  - master
#install:
#  - ./scripts/install_deps.sh
script:
  - cmake ./
  - make
  - doxygen ./Doxyfile
